# -*- mode: python ; coding: utf-8 -*-
# Linux-specific PyInstaller spec file
# Build with: pyinstaller RogueSignalProtocol-linux.spec

# All rsp subpackages must be listed for PyInstaller to discover them.
# Kept in sync with RogueSignalProtocol.spec (the Windows spec); if these drift,
# the binary fails at runtime with "ModuleNotFoundError: No module named 'rsp'".
rsp_hiddenimports = [
    'rsp',
    'rsp.combat',
    'rsp.combat.combat',
    'rsp.combat.inventory',
    'rsp.combat.turn_manager',
    'rsp.core',
    'rsp.core.config',
    'rsp.core.data',
    'rsp.core.data_loading',
    'rsp.core.engine',
    'rsp.core.errors',
    'rsp.core.file_paths',
    'rsp.core.loop',
    'rsp.core.platform',
    'rsp.core.session',
    'rsp.core.state',
    'rsp.core.version',
    'rsp.entities',
    'rsp.entities.base',
    'rsp.entities.characters',
    'rsp.entities.enemies',
    'rsp.entities.enums',
    'rsp.entities.player',
    'rsp.entities.position',
    'rsp.input',
    'rsp.input.actions',
    'rsp.input.analog',
    'rsp.input.base',
    'rsp.input.coordinates',
    'rsp.input.device_tracker',
    'rsp.input.dialogue',
    'rsp.input.gamepad',
    'rsp.input.gameplay',
    'rsp.input.handler',
    'rsp.input.mappings',
    'rsp.input.modals',
    'rsp.level',
    'rsp.level.coordinator',
    'rsp.level.generator',
    'rsp.level.layout',
    'rsp.level.map',
    'rsp.level.pathfinding',
    'rsp.level.placement',
    'rsp.level.structure',
    'rsp.level.tactical',
    'rsp.level.visibility',
    'rsp.rendering',
    'rsp.rendering.base',
    'rsp.rendering.coordinates',
    'rsp.rendering.core',
    'rsp.rendering.dimensions',
    'rsp.rendering.font_loader',
    'rsp.rendering.glyphs',
    'rsp.rendering.graphics',
    'rsp.rendering.particles',
    'rsp.rendering.tiles',
    'rsp.rendering.ui',
    'rsp.rendering.utils',
    'rsp.systems',
    'rsp.systems.achievement_popups',
    'rsp.systems.achievements',
    'rsp.systems.ascension',
    'rsp.systems.audio',
    'rsp.systems.death',
    'rsp.systems.metrics',
    'rsp.systems.persistence',
    'rsp.systems.save',
    'rsp.ui',
    'rsp.ui.common',
    'rsp.ui.dialogue',
    'rsp.ui.help_content',
    'rsp.ui.help_hints',
    'rsp.ui.info_panel',
    'rsp.ui.menu_about',
    'rsp.ui.menu_achievements',
    'rsp.ui.menu_ascension',
    'rsp.ui.menu_background',
    'rsp.ui.menu_base',
    'rsp.ui.menu_controls',
    'rsp.ui.menu_graphics_preview',
    'rsp.ui.menu_help_graphics',
    'rsp.ui.menu_help_lore',
    'rsp.ui.menu_main',
    'rsp.ui.menu_settings',
    'rsp.ui.menu_utilities',
    'rsp.ui.menus',
    'rsp.ui.message_log',
    'rsp.ui.screen_utils',
    'rsp.ui.status_bar',
    'rsp.ui.victory',
    'rsp.utils',
    'rsp.utils.autowalk',
    'rsp.utils.color_thresholds',
    'rsp.utils.colors',
    'rsp.utils.debug_export',
    'rsp.utils.inspection',
    'rsp.utils.mouse',
    'rsp.utils.narrative',
    'rsp.utils.story',
    'rsp.utils.unicode',
]

a = Analysis(
    ['RogueSignalProtocol.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=rsp_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='RogueSignalProtocol',  # No .exe extension on Linux
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='logo.png',  # PNG for Linux instead of .ico
)
